### ISSUE TITLE
Predict does not work

### ISSUE THREAD

**Issue by alphamupsiomega** [amirziai/sklearnflask#2]
Train works for me, but going to /predict returns this error page:

Method Not Allowed
The method is not allowed for the requested URL.

How can this be solved?

**Comment by amir-ziai-zefr** [comment]
@mikalyoung You can [only POST](https://github.com/amirziai/sklearnflask/blob/master/main.py#L27) to predict. Are you getting the error for GET or POST?

**Comment by alphamupsiomega** [comment]
How does one make a prediction via POST?

**Comment by amirziai** [comment]
@mikalyoung you can use an application like [Postman](https://www.getpostman.com/) or use `requests` or `urllib` in Python.

See this for more details and an example in Python: https://gist.github.com/amirziai/505449d1ebeff78240e525ac5f6fa155
