### ISSUE TITLE
reindex columns

### ISSUE THREAD

**Issue by lorenzori** [amirziai/sklearnflask#3]
hey, thoguht to give you a heads up. When you do this operation:
```
for col in model_columns:
          if col not in query.columns:
               query[col] = 0
```

you can actually use the reindex method:
`query = query.reindex(columns=model_columns, fill_value=0)`

**Comment by amirziai** [comment]
This is awesome. Thanks for pointing it out. Just updated the code in the repo:
https://github.com/amirziai/sklearnflask/blob/master/main.py#L34-L36

For anyone interested here's how this works:
https://gist.github.com/amirziai/da1a1bc9f7b38de599903eb5b123e033
